### ISSUE TITLE
Add ability to specify severity level in config file

### ISSUE THREAD

**Issue by jonrohan** [brigade/scss-lint#102]
I would like to specify severity level in my `.scss-lint.yml` config. For example

``` yml
SelectorDepth:
  enabled: true
  severity: error

IdWithExtraneousSelector:
  enabled: false
  severity: warning
```
