### ISSUE TITLE
Comma separated property values on separate lines? 

### ISSUE THREAD

**Issue by chris-dura** [brigade/scss-lint#106]
I _rarely_ find a need to use this pattern, but when I do, it improves readability significantly.

``` scss
.widget {
   background: 
      top repeat-x url("top-image.jpg"),
      right repeat-y url("right-image.jpg"),
      bottom repeat-x url("bottom-image.jpg"),
      left repeat-y url("left-image.jpg");
}
```

Thought I'd "take the temperature of the room" to see if others used this enough in their own projects to warrant an enhancement to `TrailingSemicolonAfterPropertyValue`; which currently reports lint with this pattern.
