### ISSUE TITLE
ZeroUnit catches values in data uri

### ISSUE THREAD

**Issue by nschonni** [brigade/scss-lint#108]
The following (shortened for post) data URI catches with "`0Kw` should be written without units as `0`"

``` scss
    .youtube {
        background-image: url("data:image/png;base64,0Kw+G=");
        min-width: 38px;
    }
```
