### ISSUE TITLE
PropertySortOrder complains for vendor properties with no standard property

### ISSUE THREAD

**Issue by nschonni** [brigade/scss-lint#110]
Currently the parser complains when it encounters vendor'd properties that don't have a standard property to follow.

``` scss
.foo {
  -webkit-font-smoothing: antialiased;
  -webkit-text-stroke: 1px transparent;
  color: #fff
}
```

These are non-standard so maybe excluding the files is the best approach for now
