### ISSUE TITLE
Add Option for Multiple Spaces After Colon in SpaceAfterPropertyColon

### ISSUE THREAD

**Issue by jfelchner** [brigade/scss-lint#115]
I know this is fairly anal, but when I'm doing my CSS, I prefer to have all of the values lined up with each other inside of a single rule.  For example:

``` css
.button {
  margin:      0;
  padding-top: 9px;
  font-size:   14px;
}
```

Personally I think this looks much better and is literally 7 keystrokes for me to do the alignment in vim.

I'd really like it if `SpaceAfterPropertyColon` threw an error if there were _zero_ spaces, but had an option to allow _multiple_ spaces.
