### ISSUE TITLE
Cannot Disable PropertySortOrder

### ISSUE THREAD

**Issue by iansinnott** [brigade/scss-lint#132]
I have the following `scss-lint.yml` one directory above my sass files:

``` yml
linters:
  PropertySortOrder:
    enabled: false
```

Unfortunately I still get the "Properties should be sorted in alphabetical order" error when I lint. I'm using scss-lint through Syntastic for Vim, but I get the same errors when running via the command line as well:

``` sh
scss-lint -c scss-lint.yml sass/style.scss
```

Is there another configuration option that might be interfering or is this a bug?
