### ISSUE TITLE
1 line selector with 1 property

### ISSUE THREAD

**Issue by lifeiscontent** [brigade/scss-lint#14]
is there an option to use everything from property_format_linter

except having it error on a rule like this?

``` scss
.proceed { text-align: right; }
```
