### ISSUE TITLE
DuplicateRoot: @keyframe values report as lint.

### ISSUE THREAD

**Issue by chris-dura** [brigade/scss-lint#145]
A typical vendor-prefixed keyframe pattern:

``` scss
@-moz-keyframes spin {
   0% { -moz-transform: rotate(0); }
   100% { -moz-transform: rotate(360deg); }
}
@-ms-keyframes spin {
   0% { -ms-transform: rotate(0); }
   100% { -ms-transform: rotate(360deg); }
}
@-o-keyframes spin {
   0% { -o-transform: rotate(0); }
   100% { -o-transform: rotate(360deg); }
}
@-webkit-keyframes spin {
   0% { -webkit-transform: rotate(0); }
   100% { -webkit-transform: rotate(360deg); }
}
@keyframes spin {
   0% { transform: rotate(0); }
   100% { transform: rotate(360deg); }
}
```

The `0%` and `100%` for each block are treated as "root rules", and throws this:

``` scss
src/sass/module/_spinner.scss:75 [W] Merge root rule `0%` with identical rule on line 71
src/sass/module/_spinner.scss:76 [W] Merge root rule `100%` with identical rule on line 72
...
src/sass/module/_spinner.scss:87 [W] Merge root rule `0%` with identical rule on line 71
src/sass/module/_spinner.scss:88 [W] Merge root rule `100%` with identical rule on line 72

```
