### ISSUE TITLE
Parent selector linter causes warnings on concatenated classes

### ISSUE THREAD

**Issue by Anahkiasen** [brigade/scss-lint#201]
This type of code is currently throwing a warning from the new parent selector linter:

``` scss
.icon {
    &-small {
        @extend %icon;
        font-size: 1rem;
    }

    &-large {
        @extend %icon;
        font-size: 2rem;
    }
}
```

But in this case the `&` is necessary, otherwise the generated selectors are `.icon -small` and `.icon -large`.
