### ISSUE TITLE
Add linter for double semicolons

### ISSUE THREAD

**Issue by lencioni** [brigade/scss-lint#208]
The following SCSS will currently not produce a warning, but it would be nice if it did:

``` scss
p {
  margin: 0;;
}
```
