### ISSUE TITLE
Compress CSS Hex values issue

### ISSUE THREAD

**Issue by lifeiscontent** [brigade/scss-lint#21]
The compress CSS hex values linter says I should compress this:

``` css
body { color: #3488C9; }
```

and

``` css
body { color: #E8E4E4; }
```
