### ISSUE TITLE
SingleLinePerSelector not liking preceding comma sequences

### ISSUE THREAD

**Issue by doertedev** [brigade/scss-lint#234]
OHAI.

Under time pressure right now, but this style is not being liked by the Linter:

``` scss

    .weekday-label
    , span.day
    , .month-label
    {
        text-align: center;
        padding: 0;
    }
```

Is there a way to let this pass? :) Greetings.
