### ISSUE TITLE
UrlQuotes breaks for base64 encoded background-url's

### ISSUE THREAD

**Issue by bartveneman** [brigade/scss-lint#238]
The UrlQuotes linter throws an error when I have is enabled and have a background like 

``` scss
html {
    background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAICAYAAADeM14FAAAAHUlEQVQIW2N48eLFfwYoQGYTACClKMoxBPADdGsB5L0dufB1hg8AAAAASUVORK5CYII=) white;
}
```

Using quotes for data encoded images doesn't work, but I'd like to be able to use them on urls to images.
