### ISSUE TITLE
!default and !important declarations

### ISSUE THREAD

**Issue by ArmorDarks** [brigade/scss-lint#244]
Just a small proposal to add checking weither `!default` and `!important` declarations formatted properly

Examples:

``` scss
.test {
  border: 0!important ;
}
```

against

``` scss
.test {
  border: 0 !important;
}
```

Or even errors detection like:

``` scss
.test {
  border: 0 ! important;
}
```

or

``` scss
.test {
  border: 0 !impant;
}
```
