### ISSUE TITLE
Necessary parent selector when has two (&)

### ISSUE THREAD

**Issue by diegoleme** [brigade/scss-lint#248]
This case requires the parent selector:

``` scss
.tags {
  &-item {
    display: inline;

    & + &:before {
      color: #ccc;
      content: ' • ';
    }
  }
}
```
