### ISSUE TITLE
app/assets/stylesheets/www/listings/show.scss:29: trailing whitespace.

### ISSUE THREAD

**Issue by lifeiscontent** [brigade/scss-lint#25]
I'm getting this error on a rule that looks like this:

``` scss
    .main {
        @media #{$medium} {
            background: $primary-white;
            clear: left;
            border-top: 1px solid #dad7d7;
        }
    }
```
