### ISSUE TITLE
QualifyingElement config values ignored

### ISSUE THREAD

**Issue by paulrobertlloyd** [brigade/scss-lint#286]
(v0.30.0) With the config value:

``` yaml
QualifyingElement:
  enabled: true
  allow_with_attribute: true
```

…I get the following result:

``` bash
source/_stylesheets/base/_text.scss:27 [W] QualifyingElement: Avoid qualifying attribute selectors with an element.
```

…where the css is:

``` css
abbr[title]:hover {
    border-bottom: 1px dotted rgba($c__neutral-2, 0.5);
    cursor: help;
}
```

It seems `QualifyingElement` config is being ignored.
