### ISSUE TITLE
Error when running scss-lint - No lint errors and task is not failing grunt

### ISSUE THREAD

**Issue by HNygard** [brigade/scss-lint#290]
```
$ grunt scsslint
Running "scsslint:allFiles" (scsslint) task
Running scss-lint on allFiles
>> scss-lint failed with error code: 1
>> and the following message:Error: Command failed:

Done, without errors.
```

Two problems
- No lint errors displayed
- The task does not return failed in Grunt (Grunt still thinks the build i fine)

I'm running on Windows. If I run the command from the debug/verbose version below, than scss-lint returns a lot of lint errors and exists with exit code 1

With debug and verbose (grunt scsslint --debug --verbose --no-color), the list of SCSS files was cut down to only 3 (long list of about 100 files):

```
Initializing
Command-line options: --debug=1, --verbose, --no-color

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.

Registering "grunt-contrib-copy" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-contrib-copy\package.json...OK
Parsing c:\myPath\node_modules\grunt-contrib-copy\package.json...OK
Loading "copy.js" tasks...OK
+ copy

Registering "grunt-contrib-concat" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-contrib-concat\package.json...OK
Parsing c:\myPath\node_modules\grunt-contrib-concat\package.json...OK
Loading "concat.js" tasks...OK
+ concat

Registering "grunt-contrib-uglify" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-contrib-uglify\package.json...OK
Parsing c:\myPath\node_modules\grunt-contrib-uglify\package.json...OK
Loading "uglify.js" tasks...OK
+ uglify

Registering "grunt-contrib-compass" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-contrib-compass\package.json...OK
Parsing c:\myPath\node_modules\grunt-contrib-compass\package.json...OK
Loading "compass.js" tasks...OK
+ compass

Registering "grunt-contrib-jshint" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-contrib-jshint\package.json...OK
Parsing c:\myPath\node_modules\grunt-contrib-jshint\package.json...OK
Loading "jshint.js" tasks...OK
+ jshint

Registering "grunt-contrib-cssmin" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-contrib-cssmin\package.json...OK
Parsing c:\myPath\node_modules\grunt-contrib-cssmin\package.json...OK
Loading "cssmin.js" tasks...OK
+ cssmin

Registering "grunt-contrib-connect" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-contrib-connect\package.json...OK
Parsing c:\myPath\node_modules\grunt-contrib-connect\package.json...OK
Loading "connect.js" tasks...OK
+ connect

Registering "grunt-contrib-clean" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-contrib-clean\package.json...OK
Parsing c:\myPath\node_modules\grunt-contrib-clean\package.json...OK
Loading "clean.js" tasks...OK
+ clean

Registering "grunt-contrib-htmlmin" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-contrib-htmlmin\package.json...OK
Parsing c:\myPath\node_modules\grunt-contrib-htmlmin\package.json...OK
Loading "htmlmin.js" tasks...OK
+ htmlmin

Registering "grunt-contrib-imagemin" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-contrib-imagemin\package.json...OK
Parsing c:\myPath\node_modules\grunt-contrib-imagemin\package.json...OK
Loading "imagemin.js" tasks...OK
+ imagemin

Registering "grunt-contrib-watch" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-contrib-watch\package.json...OK
Parsing c:\myPath\node_modules\grunt-contrib-watch\package.json...OK
Loading "watch.js" tasks...OK
+ watch

Registering "grunt-contrib-compress" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-contrib-compress\package.json...OK
Parsing c:\myPath\node_modules\grunt-contrib-compress\package.json...OK
Loading "compress.js" tasks...OK
+ compress

Registering "grunt-usemin" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-usemin\package.json...OK
Parsing c:\myPath\node_modules\grunt-usemin\package.json...OK
Loading "usemin.js" tasks...OK
+ usemin, useminPrepare

Registering "grunt-filerev" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-filerev\package.json...OK
Parsing c:\myPath\node_modules\grunt-filerev\package.json...OK
Loading "filerev.js" tasks...OK
+ filerev

Registering "grunt-open" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-open\package.json...OK
Parsing c:\myPath\node_modules\grunt-open\package.json...OK
Loading "open.js" tasks...OK
+ open

Registering "grunt-ngmin" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-ngmin\package.json...OK
Parsing c:\myPath\node_modules\grunt-ngmin\package.json...OK
Loading "ngmin.js" tasks...OK
+ ngmin

Registering "grunt-connect-proxy" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-connect-proxy\package.json...OK
Parsing c:\myPath\node_modules\grunt-connect-proxy\package.json...OK
Loading "connect_proxy.js" tasks...OK
+ configureProxies

Registering "grunt-angular-templates" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-angular-templates\package.json...OK
Parsing c:\myPath\node_modules\grunt-angular-templates\package.json...OK
Loading "angular-templates.js" tasks...OK
+ ngtemplates

Registering "grunt-htmlrefs" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-htmlrefs\package.json...OK
Parsing c:\myPath\node_modules\grunt-htmlrefs\package.json...OK
Loading "grunt-htmlrefs.js" tasks...OK
+ htmlrefs

Registering "grunt-grunticon" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-grunticon\package.json...OK
Parsing c:\myPath\node_modules\grunt-grunticon\package.json...OK
Loading "grunticon.js" tasks...OK
+ grunticon

Registering "grunt-scss-lint" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-scss-lint\package.json...OK
Parsing c:\myPath\node_modules\grunt-scss-lint\package.json...OK
Loading "scss-lint.js" tasks...OK
+ scsslint

Registering "grunt-modernizr" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-modernizr\package.json...OK
Parsing c:\myPath\node_modules\grunt-modernizr\package.json...OK
Loading "modernizr.js" tasks...OK
+ modernizr

Registering "grunt-regex-replace" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-regex-replace\package.json...OK
Parsing c:\myPath\node_modules\grunt-regex-replace\package.json...OK
Loading "regex-replace.js" tasks...OK
+ regex-replace
Initializing config...OK

Registering "grunt-connect-proxy" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-connect-proxy\package.json...OK
Parsing c:\myPath\node_modules\grunt-connect-proxy\package.json...OK
Loading "connect_proxy.js" tasks...OK
+ configureProxies

Registering "grunt-angular-templates" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-angular-templates\package.json...OK
Parsing c:\myPath\node_modules\grunt-angular-templates\package.json...OK
Loading "angular-templates.js" tasks...OK
+ ngtemplates

Registering "grunt-scss-lint" local Npm module tasks.
Reading c:\myPath\node_modules\grunt-scss-lint\package.json...OK
Parsing c:\myPath\node_modules\grunt-scss-lint\package.json...OK
Loading "scss-lint.js" tasks...OK
+ scsslint
Loading "Gruntfile.js" tasks...OK
+ build, default, server

Running tasks: scsslint

Running "scsslint" task
[D] Task source: c:\myPath\node_modules\grunt-scss-lint\tasks\scss-lint.js

Running "scsslint:allFiles" (scsslint) task
[D] Task source: c:\myPath\node_modules\grunt-scss-lint\tasks\scss-lint.js
Verifying property scsslint.allFiles exists in config...OK
Files: src/a/a.mobile.scss, src/a/a.scss, (...), src/t/t.scss -> allFiles
Options: config=".scss-lint.yml", reporterOutput="scss-lint-report.xml", bundleExec=false, colorizeOutput, compact=false
scss-lint options: config=".scss-lint.yml", reporterOutput="scss-lint-report.xml", bundleExec=false, colorizeOutput, compact=false
Running scss-lint on allFiles
[D] Run command: scss-lint -c .scss-lint.yml src/a/a.mobile.scss src/a/a.scss (...) src/t/t.scss
>> scss-lint failed with error code: 1
>> and the following message:Error: Command failed:

Done, without errors.
```

.scss-lint.yml

```
# Default application configuration that all configurations inherit from.
linters:
  BorderZero:
    enabled: true

  CapitalizationInSelector:
    enabled: true

  ColorKeyword:
    enabled: true

  Comment:
    enabled: false

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true

  EmptyLineBetweenBlocks:
    enabled: false

  EmptyRule:
    enabled: true

  HexFormat:
    enabled: true

  IdWithExtraneousSelector:
    enabled: true

  Indentation:
    enabled: true
    width: 4

  LeadingZero:
    enabled: false

  NameFormat:
    enabled: true

  PlaceholderInExtend:
    enabled: true

  PropertySortOrder:
    enabled: true

  PropertySpelling:
    enabled: true
    extra_properties: []

  SelectorDepth:
    enabled: true
    max_depth: 4

  Shorthand:
    enabled: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: double_quotes# or single_quotes 

  TrailingSemicolonAfterPropertyValue:
    enabled: true

  UrlQuotes:
    enabled: true

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false
```
