### ISSUE TITLE
DuplicateProperty doesn't work in nested styles

### ISSUE THREAD

**Issue by roadhump** [brigade/scss-lint#295]
I have a code to lint 

``` scss
div {
    margin: 1em;
    margin: 2em;
}


p {
    .zz {
        margin: 1em;
        margin: 2em;
    }
}
```

and result 

```
_test.scss:3 [W] DuplicateProperty: Property `margin` already defined on line 2
```

Now I get only one warning, it looks like it doesn't check in nested expressions.
