### ISSUE TITLE
property_format_linter.rb:27: undefined (?...) sequence: / (RegexpError)

### ISSUE THREAD

**Issue by derwiki** [brigade/scss-lint#31]
``` bash
$ g ci
Running pre_commit checks
  Checking author_name........................OK
/Users/adam/.rvm/gems/ruby-1.9.3-p448/gems/scss-lint-0.7.1/lib/scss_lint/linter/property_format_linter.rb:27: undefined (?...) sequence: / (RegexpError)
      ^\s*[^:]+(?<!\s):\s       # property name, colon not preceded by a space, one space
        (                       # followed by
          (?-mix:(\S+\s)*\S+);          # property and terminating semi-colon eg. a b c;
          |                     # or
          (((?-mix:(\S+\s)*\S+)\s)?\{)  # nested property, optional value, trailing curly
        )
    /
        from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from /Users/adam/.rvm/gems/ruby-1.9.3-p448/gems/scss-lint-0.7.1/lib/scss_lint.rb:19
        from /Users/adam/.rvm/gems/ruby-1.9.3-p448/gems/scss-lint-0.7.1/lib/scss_lint.rb:18:in `each'
        from /Users/adam/.rvm/gems/ruby-1.9.3-p448/gems/scss-lint-0.7.1/lib/scss_lint.rb:18
        from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
        from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:36:in `require'
        from /Users/adam/.rvm/gems/ruby-1.9.3-p448/gems/overcommit-0.2.2/lib/overcommit/plugins/pre_commit/scss_lint.rb:8:in `run_check'
        from /Users/adam/.rvm/gems/ruby-1.9.3-p448/gems/overcommit-0.2.2/lib/overcommit/git_hook.rb:74:in `run_and_filter_check'
        from /Users/adam/.rvm/gems/ruby-1.9.3-p448/gems/overcommit-0.2.2/lib/overcommit/git_hook.rb:33:in `run'
        from /Users/adam/.rvm/gems/ruby-1.9.3-p448/gems/overcommit-0.2.2/lib/overcommit/reporter.rb:14:in `with_status'
        from /Users/adam/.rvm/gems/ruby-1.9.3-p448/gems/overcommit-0.2.2/lib/overcommit/git_hook.rb:32:in `run'
        from /Users/adam/.rvm/gems/ruby-1.9.3-p448/gems/overcommit-0.2.2/lib/overcommit/git_hook.rb:24:in `each'
        from /Users/adam/.rvm/gems/ruby-1.9.3-p448/gems/overcommit-0.2.2/lib/overcommit/git_hook.rb:24:in `run'
        from /Users/adam/.rvm/gems/ruby-1.9.3-p448/gems/overcommit-0.2.2/lib/overcommit/utils.rb:11:in `run_hooks'
        from /Users/adam/.rvm/gems/ruby-1.9.3-p448/gems/overcommit-0.2.2/lib/overcommit/utils.rb:11:in `each'
        from /Users/adam/.rvm/gems/ruby-1.9.3-p448/gems/overcommit-0.2.2/lib/overcommit/utils.rb:11:in `run_hooks'
        from .git/hooks/pre-commit:8
```

on the file:

``` css
@import 'mixins';
@import 'www/shared/global';

#feedback-modal {
  width: 528px;
  height: 500px;

  .modalCloseImg {
    background: image-url('common/modal-close.png') no-repeat top left;
    cursor: pointer;
    display: block;
    height: 25px;
    position: absolute;
    right: 16px;
    top: 10px;
    width: 25px;
    z-index: 10;
  }

  .simplemodal-data {
    @include border-radius(10px);
    @include box-shadow(0 0 5px 0 rgba(0,0,0,.5));
    background: #fff;
    color: #333;
    font-size: 12px;
    padding: 20px;
  }

  .simplemodal-wrap .feedback-form {
    padding: 80px 50px 50px;

    .listy {
      background: image-url('apartmentlist/feedback-listy.png') no-repeat top left;
      height: 86px;
      left: 15px;
      position: absolute;
      top: 25px;
      width: 121px;
    }

    .title {
      color: #333;
      font-family: 'HelveticaNeue-Light', 'Helvetica Neue Light', 'Helvetica Neue', sans-serif;
      font-size: 25px;
      font-weight: 300;
      margin-bottom: 30px;
      margin-left: 100px;
    }

    .field {
      @include clearfix;
    }

    label {
      float: left;
      font-weight: bold;
      margin-right: 10px;
      margin-top: 10px;
      text-align: right;
      text-transform: uppercase;
      width: 85px;
    }

    .name,
    .email,
    textarea {
      @include contact-input(310px);
      float: left;
    }

    .error,
    .error_message {
      background: #fce6e5;
      border-color: #f99090;
    }

    textarea {
      height: 150px;
    }

    .error_message {
      @include border-radius(4px);
      display: none;
      font-size: 14px;
      margin-top: 5px;
      padding: 11px;
    }
    .submit {
      @include button;
      float: right;
      padding: 10px 15px;
    }
  }
}
#recaptcha_area {
  float: right;
}
```
