### ISSUE TITLE
Content entities are mistakenly identified as colors

### ISSUE THREAD

**Issue by anthonyryan1** [brigade/scss-lint#317]
## Input

``` scss
.test:after {
  content: '&#10004;';
}

```
## Output

```
[W] HexValidation: Colors must have either three or six digits: `#10004`
```
