### ISSUE TITLE
Disable linter fails after comment on previous line

### ISSUE THREAD

**Issue by bartveneman** [brigade/scss-lint#373]
I use a commenting system with numbers, so I don't have to put all of them inline, which can become really sloppy:

````scss
// 1. Some comment about my background
.foo {
  background: 0; // [1]
  border-radius: 0;
}
````

When using an inline scss-lint:disable comment, it breaks when it comes right after a line with this comment, like so:

````scss
// 1. Some comment about my background
.foo {
  background: none; // [1]
  // scss-lint:disable ImportantRule
  border-radius: 0 !important;
  // scss-lint:enable ImportantRule
}
````
It now reports an error on line 5 to not use `!important`. Removing the `// [1]` comment makes the inline disable statement work like it should. The same goes for when I wrap the whole selector in the toggling comments.
