### ISSUE TITLE
PropertUnits global merging default set

### ISSUE THREAD

**Issue by imcnally** [brigade/scss-lint#422]
Hey @sds,

Just noticed that PropertyUnits is merging default and local settings for `global`. I tested it by printing the config properties. When I set my local config to:

```yml
  PropertyUnits:
    enabled: true
    global: ['hey']
    properties:
      line-height: []
```

I get: 

```
{
  "enabled"=>true,
  "global"=>["ch", "em", "ex", "rem", "cm", "in", "mm", "pc", "pt", "px", "q", "vh", "vw", "vmin", "vmax", "deg", "grad", "rad", "turn", "ms", "s", "Hz", "kHz", "dpi", "dpcm", "dppx", "%", "hey"],
  "properties"=>{"line-height"=>[]}
}
```

You'll notice my fake unit `'hey'` on the end of the global list.

Merging seems baked into config.rb. It may work for other circumstances, but it works against a specific allowed list in this case.
