### ISSUE TITLE
DeclarationOrder linter doesn't work inside media queries

### ISSUE THREAD

**Issue by mrpavlikov** [brigade/scss-lint#423]
Not sure if its a bug or not, but it seems to be. Following code reasonably fails:

```scss
@mixin mix1() {
    color: #ccc;
}

@mixin mix2() {
    border: #ccc;
}

.b-map {
    @include mix1();

    width: 100%;
    height: 100%;

    @include mix2();
}
```

But if I wrap `.b-map` contents into media query lint passes:

```scss
@mixin mix1() {
    color: #ccc;
}

@mixin mix2() {
    border: #ccc;
}

.b-map {
    @media screen and (max-width: 600px) {
        @include mix1();

        width: 100%;
        height: 100%;

        @include mix2();
    }
}
```
