### ISSUE TITLE
PropertyUnits not linting?

### ISSUE THREAD

**Issue by chris-dura** [brigade/scss-lint#425]
The `PropertyUnits` linter in `0.37.0` doesn't seem to be linting for me...
```yml
# scss-lint.yml

PropertyUnits:
    enabled: true
    global: ['em', 'rem', '%'] # Allow relative units globally
```

```scss
// test.scss

.widget {
   width: 10px;
}
```
