### ISSUE TITLE
Should VariableForProperty report lint for `transparent` and `inherit`?

### ISSUE THREAD

**Issue by chris-dura** [brigade/scss-lint#426]
```yml
  VariableForProperty:
    enabled: true
    properties:
      - color
      - font
```
```scss
.foo {
   color: inherit;
   font: inherit;
}

.bar {
   color: transparent;
}
```
This reports lint, but I'm not sure it should?
Similar to my reasoning here: https://github.com/brigade/scss-lint/issues/376#issue-59166822

Writing this seems like a smell...
```scss
$inherit: inherit;
$transparent: transparent;

.foo {
   color: $inherit;
   font: $inherit;
}

.bar {
   color: $transparent;
}
```
