### ISSUE TITLE
Inline disable/enable linters are being ignored

### ISSUE THREAD

**Issue by peavers** [brigade/scss-lint#448]
Was working fine a couple of weeks back, we have since updated our dev environments and inline linters seem to be ignored 

```CSS
// scss-lint:disable PropertySortOrder
.page-wrapper {
  margin: 0 auto -200;
  min-height: 100%;
  height: auto;
}
// scss-lint:enable PropertySortOrder
```

Still returns:

```
PropertySortOrder:  Properties should be sorted according to the custom order specified by the configuration
```

I note the return message is now "according to the custom order..." whereas it used to tell us the custom order.
