### ISSUE TITLE
Problem with Custom PropertySortOrder

### ISSUE THREAD

**Issue by meowsus** [brigade/scss-lint#478]
Consider this group of css properties:

```
.selector {
    position: absolute;
    top:    0;
    bottom: 0;
    padding: 20px;
    width: $drawer-narrow-width;
    background: $drawer-bg-color;
    transition: left 0.25s ease-out;
    overflow-y: auto;
    box-sizing: border-box;
}
```

in conjunction with the following PropertySortOrder settings:

```
PropertySortOrder:
  enabled: true
  ignore_unspecified: false
  separate_groups: false
  order:
    - display
    -
    - position
    - top
    - right
    - bottom
    - left
    - z-index
    -
    - margin
    - margin-top
    - margin-right
    - margin-bottom
    - margin-left
    -
    - margin-collapse
    - margin-top-collapse
    - margin-right-collapse
    - margin-bottom-collapse
    - margin-left-collapse
    -
    - padding
    - padding-top
    - padding-right
    - padding-bottom
    - padding-left
    -
    - width
    - height
    - max-width
    - max-height
    - min-width
    - min-height
    -
    - float
    - clear
    -
    - color
    -
    - font
    - font-size
    - font-style
    - font-family
    - font-weight
    - font-smoothing
    -
    - line-height
    - letter-spacing
    - word-spacing
    -
    - text-align
    - text-indent
    - text-shadow
    - text-overflow
    - text-rendering
    - text-transform
    - text-decoration
    - text-size-adjust
    -
    - word-break
    - word-wrap
    -
    - white-space
    -
    - background
    - background-size
    - background-color
    - background-image
    - background-repeat
    - background-position
    - background-attachment
    -
    - border
    - border-top
    - border-right
    - border-bottom
    - border-left
    -
    - border-image
    - border-spacing
    - border-collapse
    -
    - border-color
    - border-top-color
    - border-right-color
    - border-bottom-color
    - border-left-color
    -
    - border-style
    - border-top-style
    - border-right-style
    - border-bottom-style
    - border-left-style
    -
    - border-width
    - border-top-width
    - border-right-width
    - border-bottom-width
    - border-left-width
    -
    - border-radius
    - border-top-right-radius
    - border-bottom-right-radius
    - border-bottom-left-radius
    - border-top-left-radius
    - border-radius-topright
    - border-radius-bottomright
    - border-radius-bottomleft
    - border-radius-topleft
    -
    - box-shadow
```

The `ignored_unspecified: false` setting should allow any property, in any order, to be placed at the bottom of `.selector`s property block. If you try to lint the aforementioned code you'll notice that there is no way to get the last three properties to pass the linting.

**Comment by sds** [comment]
Hey @meowsus,

You want `ignore_unspecified: true`, since you want to ignore `transition`/`overflow-y`/`box-sizing` etc. since they are not defined in your custom `order`. 

Is there something in the documentation that would make this clearer?

**Comment by meowsus** [comment]
`ignore_unspecified: false` seems to work almost perfectly for what I need, for the most part it allows all properties defined in the list to be forced in it's proper order, then, all other properties that aren't part of the defined order, should be put below the defined property order.

With `ignore_unspecified: true` the uncaught properties can be placed pretty much anywhere, because they are just ignored.

What I'm looking for is, first, the defined order is enforced then, second, the properties that are not defined are forced to the bottom of the block, in any order.

The documentation made it seem like that was the concept behind `ignore_unspecified: false`

**Comment by sds** [comment]
Sorry @meowsus, I misunderstood what you were getting at.

The problem here is that Ruby's `Array#sort` method is not stable. As a result, the unspecified properties could have their relative order shuffled. When I run your example above, this is the order it expects:

```scss
.selector {
    position: absolute;
    top:    0;
    bottom: 0;
    padding: 20px;
    width: $drawer-narrow-width;
    background: $drawer-bg-color;
    overflow-y: auto;
    transition: left 0.25s ease-out; // <-- Swapped places with overflow-y
    box-sizing: border-box;
}
```

I'll implement a fix shortly.
