### ISSUE TITLE
ColorVariable should flag uses of rgb/rgba/hsl/hsla

### ISSUE THREAD

**Issue by cH40z-Lord** [brigade/scss-lint#488]
Today I've discovered a strange inconsistency between color definitions. SCSS-Lint is throwing a warning whenever you try to use a color definition like `#fff` outside of a SCSS variable. However, this is not true for colors defined via `rgb()` and `rgba()`, which feels kinda strange and not what I expect.

```css
.foo {
  // warning: foo.scss:2 [W] ColorVariable: Color literals like `#fff` should only be used in variable declarations; they should be referred to via variable everywhere else.
  backgorund-color: #fff;
}

.bar {
  // no warning/error
  background-color: rgba(255, 255, 255, .5);
  //background-color: rgb(255, 255, 255);
}
```

I'd love to have an option for this as well so we can improve our SCSS code even more. What do you think?
