### ISSUE TITLE
Linter BemDepth does not exist

### ISSUE THREAD

**Issue by Undistraction** [brigade/scss-lint#493]
Running:

```
scss-lint -i BemDepth
```

Results in:

```
Linter BemDepth does not exist
```

Even if BemDepth is enabled in `.scss-lint`:

```
scss_files: 'src/sass/**/*'

linters:
  BemDepth:
    enabled: true
    max_elements: 3
    severity: error
```
