### ISSUE TITLE
Feature Request: Switch to allow mixins with content last in DeclarationOrder

### ISSUE THREAD

**Issue by Undistraction** [brigade/scss-lint#494]
Consider the following:

```
.Example {
  @include example(yes);
  width: 100%;
  
  .Icon {
    color: red;
  }

  @include bp(small-up) {
    @include example(no);
     width: 50%;

     .Icon {
       color: blue;
     }
  }
}
```

When using a mixin for rendering breakpoints, it makes more sense for it to come after any nested classes. Please supply a whitelist parameter for mixins that can come after everything else in the DeclarationOrder linter.

**Comment by lencioni** [comment]
> When using a mixin for rendering breakpoints, it makes more sense for it to come after any nested classes.

Why do you say that it makes more sense for it to come after nested classes? I believe that things should be ordered in how closely they relate to the root selector. The example you give would be better written as:

```scss
.Example {
  @include example(yes);
  width: 100%;
                           
  @include bp(small-up) {
    @include example(no);
    width: 50%;
  }
                           
  .Icon {
    color: red;
                           
    @include bp(small-up) {
      color: blue;
    }
  }
}
```
