### ISSUE TITLE
Feature request: support for LostGrid

### ISSUE THREAD

**Issue by brunowego** [brigade/scss-lint#512]
This plugin is awesome! Make compatible with [LostGrid](https://github.com/corysimmons/lost#basic-columns) will turn this a killer machine:

Messages will popup if try use something like this:
```scss
section {
  lost-utility: clearfix;
}

div {
  lost-column: 1/2;
}
```

Thanks!
