### ISSUE TITLE
Limit EmptyLineBetweenBlocks

### ISSUE THREAD

**Issue by Globegitter** [brigade/scss-lint#526]
It would be great if the `EmptyLineBetweenBlocks` could be limited to allow a maximum number of empty lines.

E.g.
```
  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true
   max_lines: 1
```

*Allowed*
```
  .class1 {
    width: 33.33333%;

    &:before {
      padding-left: 10px;
    }
```

*Not Allowed*
```
  .class1 {
    width: 33.33333%;


    &:before {
      padding-left: 10px;
    }
```
