### ISSUE TITLE
undefined method `members' for nil:NilClass - NestingDepth error

### ISSUE THREAD

**Issue by viveleroi** [brigade/scss-lint#541]
Exception: https://pste.me/#/4bijx

Our current config: https://pste.me/#/AVXTq

- SCSS-Lint version: 0.40.1
- Sass version: 3.4.16
- Ruby version: 2.0.0

The offending content, which when removed no longer triggers the issue:

    /* Key Frames */

    @include keyframes(slideInLeft) {
        0% {
            @include transform(translate(100%, 0));
            opacity: 0;
        }

        100% {
            @include transform(translate(0, 0));
            opacity: 1;
        }
    }

    @include keyframes(slideOutRight) {
        0% {
            @include transform(translate(0, 0));
            opacity: 1;
        }

        100% {
            @include transform(translate(150%, 0));
            opacity: 0;
        }
    }

    @include keyframes(hide) {
        0% {
            opacity: 1;
        }

        100% {
            opacity: 0;
        }
    }

It appears that disabling scss-lint via a comment doesn't work, so this is a blocking issue for us. I may need to try ignoring the entire file.

This seems to affect 0.40.0 as well.

**Comment by sethlopezme** [comment]
I am experiencing this issue, as well.

Exception: https://pste.me/#/JZJGN

My config: https://pste.me/#/VnLM8

- SCSS-Lint version: 0.40.1
- Sass version: 3.4.15
- Ruby version: 2.0.0

The offending code is below. I tried and failed to isolate exactly what the problem code was here.

```scss
.row {
	@include flex-container;

	// modifiers
	&.spaced {
		@include flex-spaced;
	}

	&.spread {
		@include flex-spread;
	}

	&.align-left {
		@include flex-align-left;
	}

	&.align-right {
		@include flex-align-right
	}

	&.valign-top {
		@include flex-valign-top;
	}

	&.valign-bottom {
		@include flex-valign-bottom;
	}

	&.equal-heights {
		@include flex-equal-heights
	}
}

[class*="col"] {
	&.valign-top {
		@include valign-top;
	}

	&.valign-bottom {
		@include valign-bottom;
	}

	&.valign-middle {
		@include valign-middle;
	}
}

@for $i from 1 through $grid-columns {
	$_col-size : (100%/$grid-columns * $i);

	.col-#{$i} {
		@include grid-col($i);
	}

	.offset-#{$i} {
		margin-left: $_col-size;
	}
}

@each $name, $val in $breakpoints {
	@include media(">#{$name}") {
		@for $i from 1 through $grid-columns {
			.col-#{$name}-#{$i} {
				width: (100%/$grid-columns * $i);
			}
		}
	}
}
```
