### ISSUE TITLE
enabled SpaceBetweenParens doesn't allow parameter-less functions

### ISSUE THREAD

**Issue by montchr** [brigade/scss-lint#552]
Configuration:

```yml
  SpaceBetweenParens:
    enabled: true
    spaces: 1
```

If I try to run a function like `function()` without a parameter, SpaceBetweenParens throws an error. If I add spaces, I still receive a combination of errors and will always fail because it never detects the proper number of spaces between each parenthesis. I've tried 2 and 3 spaces between parens, neither of which work.

Potentially related to #475.
