### ISSUE TITLE
inline disabling SpaceBetweenParens doesn't work

### ISSUE THREAD

**Issue by montchr** [brigade/scss-lint#553]
Related to my previous issue #552, I'm unable to work around this as there's no way to disable SpaceBetweenParens inline. I've done this fine with other linters, but this one gets ignored and the errors still occur.

```scss
// scss-lint:disable SpaceBetweenParens


@mixin o-blox-offset( $size: null ) {
  @if $size {
    margin-top: o-blox-offset-get( $size );
  } @else {
    margin-top: o-blox-offset-get();
  }
}


// scss-lint:enable SpaceBetweenParens
```

The line with `o-blox-offset-get()` still has the error:

```
assets/scss/base/global/_mixins.scss:392 [W] SpaceBetweenParens: Expected 1 space between parentheses instead of 0
assets/scss/base/global/_mixins.scss:392 [W] SpaceBetweenParens: Expected 1 space between parentheses instead of 0
```
