### ISSUE TITLE
Combinators and Ampersand and UnnecessaryParentReference

### ISSUE THREAD

**Issue by ifyoumakeit** [brigade/scss-lint#594]
SCSS shouldn't really compile `~ &` because it's doesn't do anything but `UnnecessaryParentReference` leads developers to drop the ampersands proceeding a combinator, despite it not doing what it's supposed to do in the `~ &` case.  The parent selector is nice, but maybe there should be an additional rule to use `& ~ &` when the second value starts with an ampersand.

**SCSS**
```scss
.foo {  
  & ~ & {
    background: green; // Valid
  }
  ~ & {
    background: black; // Invalid
  }
}
```
**CSS**
```css
.foo ~ .foo {
  background: green;
}
~ .foo {
  background: black;
}
```

Maybe `NecessaryParentReference`?
