### ISSUE TITLE
`at_least_one_space` for SpaceAroundOperator

### ISSUE THREAD

**Issue by ArmorDarks** [brigade/scss-lint#615]
In some situations it's better to align values around operators, but with current options `one_space # or 'no_space'` it isn't possible.

It would be great to have `at_least_one_space` option, similar to `SpaceAfterPropertyColon`

Not best example, but something like this:

``` scss
@font-face {
	font-family: $font;

	src: url($ekzo-fonts-path + '/' + $file-name + '.eot'  + $version);
	src: url($ekzo-fonts-path + '/' + $file-name + '.eot'  + $version + '#iefix') format('embedded-opentype'),
	     url($ekzo-fonts-path + '/' + $file-name + '.woff' + $version)            format('woff'),
	     url($ekzo-fonts-path + '/' + $file-name + '.ttf'  + $version);
}
```
