### ISSUE TITLE
Indentation of variables

### ISSUE THREAD

**Issue by ArmorDarks** [brigade/scss-lint#618]
Options:

``` yaml
  Indentation:
    enabled: true
    allow_non_nested_indentation: true
    character: tab
    width: 1
```

When `allow_non_nested_indentation` enabled I thinks it's naturally to expect that you could intend variables as you might need too.

But this example

``` scss
.site-header {}

	.site-logo {}

		.site-logo__link {}

	.site-nav {}

		$site-nav__item-color: #000;

		.site-nav__item {

			color: $site-nav__item-color;

		}
```

will throw

```
9: [W] Indentation:  Line should be indented 0 tabs, but was indented 2 tabs
```

I agree that it isn't best example, since you can put variable inside of selector's scope and it will fix that error. But imagine that you need to keep it out of selectors scope, to make it available to other selectors below, but in same time you want to keep that variable close to it's origin.

This definitely looks wrong (but acceptable for SCSS Lint):

``` scss
.site-header {}

	.site-logo {}

		.site-logo__link {}

	.site-nav {}

$site-nav__item-color: #000;

		.site-nav__item {

			color: $site-nav__item-color;

		}
```

I must admit that for better flexibility it would be better to assign different option for controlling variable's indentation
