### ISSUE TITLE
Concentric order linting can't make up its mind

### ISSUE THREAD

**Issue by stowball** [brigade/scss-lint#628]
When using certain flexbox properties, scss-lint often complains that properties are ordered incorrectly, so you fix it, then it complains again to switch it back. It also seems highly dependent on the other properties used in the rule. It's annoying.

Take this example:

```scss
.foo {
    display: flex;
    transition: all ease .15s;
    outline: none;
    border: 1px solid #444950;
    border-radius: 4px;
    background: #1f2128;
    padding: 8px 10px;
    width: 100%;
    text-align: center;
    text-transform: uppercase;
    text-decoration: none;
    line-height: (15 / 13);
    color: #fff;
    font-family: sans-serif;
    font-size: 13px;
    font-weight: bold;
    flex-wrap: wrap;
    align-items: center;
    justify-content: center;
}
```

scss-lint will warn that: `Properties should be ordered display, transition, outline, border, border-radius, background, padding, width, text-align, text-transform, text-decoration, line-height, color, font-family, font-size, font-weight, *align-items*, *flex-wrap*, justify-content`

Then, if you switch `align-items` and `flex-wrap` like instructed, it will warn that `Properties should be ordered display, transition, outline, border, border-radius, background, padding, width, text-align, text-transform, text-decoration, line-height, color, font-family, font-size, font-weight, *flex-wrap*, *align-items*, justify-content`

Interestingly, in this example, if just one of the other properties is removed, the warning disappears, regardless of the order of `flex-wrap` and `align-items`.

My lint rules are as follows:

```yml
linters:
    UrlFormat:
        enabled: false # allows for url(//some.domain/something)
    SelectorFormat:
        convention: 'hyphenated_BEM'
    NestingDepth:
        max_depth: 4 # Default is 3. But we're typically namespaced once.
    SelectorDepth:
        max_depth: 4
    PropertySortOrder:
        order: concentric
    Indentation:
        width: 4
        severity: error
    VendorPrefix:
        enabled: false
    NameFormat:
        enabled: true
        convention: hyphenated_lowercase
        allow_leading_underscore: true
        variable_convention: '[a-z]+([-_].+)?'
        placeholder_convention: '[a-z]+([-_].+)?'
    Comment:
        allowed: '(Dependencies|@TODO)'
    ColorVariable:
        enabled: false
```
