### ISSUE TITLE
MergeleSelector suggests merging unmergable selectors?

### ISSUE THREAD

**Issue by Vall3y** [brigade/scss-lint#657]
I have the following code:

    &_form {
      display: flex;

      > * { // Line 7
        flex-grow: 1;
      }

      > * + * {
        margin-left: $double-gutter-width;
      }
    }

I get the following error

    [W] MergeableSelector: Merge rule `> * + *` with rule on line 7

I either dont know of the proper way to merge the selectors, or MergableSelector doesn't take into account that that 
    
    > * { // Line 7
      flex-grow: 1;

      & + * {...}
    }

Will yield an whole other selector

**Comment by chris-dura** [comment]
In my test, both of these snippets produce the same CSS...

```css
&_form {
  display: flex;
}

&_form > * {
   flex-grow: 1;
}

&_form > * + * {
   margin-left: $double-gutter-width;
}
```
