### ISSUE TITLE
Invalid configuration

### ISSUE THREAD

**Issue by mrmckeb** [brigade/scss-lint#676]
Hi there,

I'm seeing the following error:
`Invalid configuration: (<unknown>): did not find expected key while parsing a block mapping at line 4 column 1`

It works fine if I remove the `exclude` section and `linters` keyword from the config. Top of config is below:
```
exclude:
 - 'www/latest/scss/base/_reset.scss'
 - 'www/latest/scss/base/_normalize.scss'

linters:
  BorderZero:
    enabled: true

  CapitalizationInSelector:
    enabled: true

  ColorKeyword:
    enabled: true

  Comment:
    enabled: true
```

It doesn't throw that error I use the below only:
```
  BorderZero:
    enabled: true

  CapitalizationInSelector:
    enabled: true

  ColorKeyword:
    enabled: true

  Comment:
    enabled: true
```
