### ISSUE TITLE
Incorrect SpaceBeforeBrace lint error

### ISSUE THREAD

**Issue by ivancuric** [brigade/scss-lint#682]
The linter often gets confused, and the only solution is to delete the brace and space, let the linter parse, and then retype the brace again. I don't see any pattern on when the bug occurs.

```Bash
main.scss:4727 [W] SpaceBeforeBrace: Opening curly brace `{` should be preceded by one space
```
![image](https://cloud.githubusercontent.com/assets/2827047/12451160/037d896c-bf88-11e5-91b8-0565fdd2064f.png)

**Comment by bartveneman** [comment]
Are you sure this is an Scss-lint issue and not one for the editor plugin you're using? Does the error also occur when you run scss-lint from the command line?

**Comment by ivancuric** [comment]
Yep, the error was from the console output.

**Comment by sds** [comment]
Hey @ivancuric,

Running the following code against `scss-lint` with the default configuration:

```scss
.installment-accordion-row {
  display: none;
  &.is-visible {
    display: table-row;
  }
}

.installment-accordion-toggle {
  color: $b1;
}
```

...I get the following correct output:

```
test.scss:3 [W] EmptyLineBetweenBlocks: Rule declaration should be preceded by an empty line
```

Thus nothing seems wrong here. The "confusion" you're referring to must be a quirk of the editor you're using (or the scss-lint plugin for that editor, neither of which this project maintains).
