### ISSUE TITLE
Exclude files for single linters

### ISSUE THREAD

**Issue by geniou** [brigade/scss-lint#69]
I have some SCSS files that are styling HTML from external libraries (e.g. jQuery plugins) that don't follow the scss-lint selector naming convention.

I could exclude these files totally, but it would be nice to exclude files for a single linter in the config - e.g. like this.

``` yml
linters:
  CapitalizationInSelector:
    exclude:
      - 'path/to/file.scss'
```

In rubocop you can do the same. What do you think? I have a prototype of this working, I could refine this and create a pull request.
