### ISSUE TITLE
missing properties

### ISSUE THREAD

**Issue by rammi987** [brigade/scss-lint#705]
Hello,
We have found a missing properties, with cost an issuse.
If we are type Post-css commands we are getting warnings for miss spell word.
Ex. font-range.

**Comment by sds** [comment]
Hey @rammi987,

Since `font-range` is not a standardized CSS property (it's provided by the `postcss-responsive-type` plugin), it doesn't make sense for SCSS-Lint to include it by default.

You can whitelist custom properties by adding them to the `extra_properties` option of the `PropertySpelling` linter, e.g.

```yaml
linters:
  PropertySpelling:
    extra_properties:
      - font-range
```

Hope that helps.
