### ISSUE TITLE
Linter proposal: disallow `position: absolute` unless first rule in the file has `position: relative/fixed`

### ISSUE THREAD

**Issue by janpaul123** [brigade/scss-lint#730]
To prevent implicit dependencies between components based on positioning. (I should still write a blog post about this.)

**Comment by srawlins** [comment]
I don't understand this. Why would this depend on the "first rule in the file?"  i.e.

```scss
a { position: relative; }

p { position: absolute; }
```
