### ISSUE TITLE
Support percentage as @keyframes selectors

### ISSUE THREAD

**Issue by tleruitte** [brigade/scss-lint#74]
Here is a sample SCSS that cause a error in scss-lint:

``` css
@keyframe my_keyframe {
    0% {
        background: none;
    }
    50% {
        background: red;
    }
}
```

Could you support percentage as keyframes selectors?
