### ISSUE TITLE
Small problem with max depth of nesting

### ISSUE THREAD

**Issue by mbatyumov** [brigade/scss-lint#748]
In sass from version 3.3.0 we can to add suffixes (for example: &-suffix or &_suffix).

And if I have the next constraint:

``` yml
NestingDepth:
  enabled: true
  max_depth: 3
  ignore_parent_selectors: false
```

I'll get an error with this code:

``` scss
.icon {
    &-user {
        &-small {
            &:hover {}
        }
    }
}
```

But after proccessing it looks great:

``` css
.icon-user-small:hover {}
```

if I set max_depth to 4, I can miss real errors. Is it possible to solve this?
