### ISSUE TITLE
Using Warning and Error Severity

### ISSUE THREAD

**Issue by oli** [brigade/scss-lint#793]
Thanks for this excellent tool. I’d like to trigger warning and error states at different values on the same linter, something like:

```
SelectorDepth:
  max_depth: 2
  severity: warning

SelectorDepth:
  max_depth: 3 # Only permitted if overriding vendor CSS
  severity: error
```

My desired output would be `[W]` for rules matching `SelectorDepth: 3` and `[E]` for rules matching `SelectorDepth:4`.

The [readme](https://github.com/brigade/scss-lint#severities) mentions `scss-lint` can return both warnings and errors, but I can’t seem to get this working on a single property. Is this supported? If so can someone share an example config please? If this is not supported, please let me know so I can add “Feature Request” to the issue title 😉 

Thanks!

**Comment by sds** [comment]
Hey @oli, thanks for suggesting ways we can improve the tool.

The format you suggest would not work because of the YAML specification itself. YAML will treat duplicate keys as overwriting previously-defined keys, for example:

```yaml
# test.yaml
linters:
  SelectorDepth:
    max_depth: 2
    severity: warning

  SelectorDepth:
    max_depth: 3 # Only permitted if overriding vendor CSS
    severity: error
```

Running the following command:
```bash
ruby -e "require 'yaml'; puts YAML.load_file('test.yaml').to_yaml"
```

You'll get:
```
---
linters:
  SelectorDepth:
    max_depth: 3 # Only permitted if overriding vendor CSS
    severity: error
```

Thus this is fundamentally not supported at the YAML level.

Thus support for this would need to be added on a per-linter basis. I'm open to pull requests but I think you might be nearing the area of "overcomplicating" your rules. Warnings have their place but I would see the example you provide as being more annoying than useful. I personally want to see output when there is an actual problem.

Hope that helps!
