### ISSUE TITLE
NestingDepth takes into consideration BEM selectors

### ISSUE THREAD

**Issue by cdreve** [brigade/scss-lint#810]
Hi all,

With the current version, is it possible for the `NestingDepth` to consider BEM selectors as nesting depth 1? If not, could this be added?

**Current config:**
```bash
 ~ scss-lint -v
scss-lint 0.49.0
```
```yml
NestingDepth:
  enabled: true
  max_depth: 1
```

**SCSS:**
```scss
.block {
  color: red;
  
    &__element {
      color: blue;
    }
}
```

**Expected result:**
In this case I would expect the NestingDepth to be 1, since this generates 2 CSS selectors that don't have any selectors within.
```scss
.block {color: red;}
.block__element {color: blue;}
```

**Actual result:** 
`NestingDepth: Nesting should be no greater than 1, but was 2`

**Note:** For linting BEM selectors we already have `BemDepth`.

Thanks
