### ISSUE TITLE
ColorKeyword erroneously finds map-get arguments

### ISSUE THREAD

**Issue by jamesarosen** [brigade/scss-lint#821]
If I have a map like
```scss
$my-colors: (
  red: #de2424,
  green: #28d424,
  blue: #2820e0
);
```
and I use it like
```scss
.some-thing {
  border-color: map-get($my-colors, green);
}
```
then the ColorKeyword checker alerts me that `green` should be written in hexadecimal form. But it isn't a color keyword here; it's a table key.

Unfortunately, I'm not sure there's a way to distinguish between that and `darken(green, 10%)`, which should be caught by ColorKeyword.
