### ISSUE TITLE
PrivateNamingConventions edge case

### ISSUE THREAD

**Issue by deioo** [brigade/scss-lint#828]
Defining a private function and using it within other functions or mixins triggers linter warnings.

So having this code:

```scss
@function _selector-to-string($selector) { ... }

@function _selector-has-feature($selector) {
  $selector: _selector-to-string($selector);

  ...
}

...

@mixin generate($selector) {
  @if _selector-has-feature($selector) {
    ...
  }
}
```

Would still throw a `Private function _xxxxx must be used in the same file it is defined` for both `_selector-to-string` and `_selector-has-feature`, even if they're used below.
