### ISSUE TITLE
Feature Request: Previous Group Threshold

### ISSUE THREAD

**Issue by thegranddesign** [brigade/scss-lint#840]
This isn't the "How many properties do I need to group anything" option that already exists, this is a more flexible (and I think better) option to have the linter decide when _any_ group needs to be grouped with a previous group.

This is best illustrated with a couple examples:

Let's say that we have a simplified property grouping of:

```
display
position
top
right
bottom
left

visibility
opacity
z-index

outline
outline-offset
outline-width
outline-style
outline-color

border
border-top
border-right
border-bottom
border-left

margin
margin-top
margin-right
margin-bottom
margin-left

padding
padding-top
padding-right
padding-bottom
padding-left

width
min-width
max-width

height
min-height
max-height

background
background-color
background-image
background-repeat
background-position
background-size
```

Currently as it stands, the following CSS would be desired by the linter:

```css
.my-class {
  display:                  absolute;

  z-index:                  1000;

  outline:                  1px dashed #ff00ff;

  border:                   10rem solid #ff0000;

  margin:                   1px 2px 3px 4px;

  padding:                  100px;

  width:                    900px;

  height:                   300px;

  background:               url('/foo/bar.jpg');
}
```

That's a lot of extra spacing and noise in my opinion.  I think that in these cases, the groups should be allowed to be collapsed and I think the rule should be:

> Look at the group before you.  Does it have less than _**threshold**_ properties and does _my group_ have less than _**threshold**_ properties?  If yes, then _allow_ (but don't _require_) it to be grouped with the previous group.

With this rule you could have something like this:

```css
.my-class {
  display:                  absolute;
  z-index:                  1000;

  outline:                  1px dashed #ff00ff;
  border:                   10rem solid #ff0000;

  margin:                   1px 2px 3px 4px;
  padding:                  100px;

  width:                    900px;
  height:                   300px;

  background:               url('/foo/bar.jpg');
}
```

Or some combination of that, however if you wanted to add some more specific `width`s and positional properties like so:

```css
.my-class {
  display:                  absolute;
  top:                      10px;
  left:                     20px;

  z-index:                  1000;

  outline:                  1px dashed #ff00ff;
  border:                   10rem solid #ff0000;

  margin:                   1px 2px 3px 4px;
  padding:                  100px;

  width:                    900px;
  min-width:                300px;
  max-width:                1200px;

  height:                   300px;

  background:               url('/foo/bar.jpg');
}
```

Then, if the `threshold` was `2`, the `width` section there would be _required_ to be broken out as a separate group from `padding` (since it's group is over the threshold) and the `height` group would be required to be broken out as well (since it's previous group is over the threshold).  And the same rules apply to the `position` section.

I think that this would allow for much more compact CSS (while still maintaining the proper order) for those times when you mainly use shorthand properties (eg `padding`) rather than longer form properties (eg `border-left-color`).
