### ISSUE TITLE
ZeroUnit needs to be disabled within `calc` functions

### ISSUE THREAD

**Issue by thegranddesign** [brigade/scss-lint#843]
Within `calc` functions, the browser doesn't like `0` without a unit.  While this doesn't make sense, at least on Webkit, the unit is required.

```css
foo {
  /* Works */
  margin-top: calc(0px - calc(50% - 1.4rem));
  /* Doesn't work */
  margin-top: calc(0 - calc(50% - 1.4rem));
}
```
