### ISSUE TITLE
Sassdoc comment compliant

### ISSUE THREAD

**Issue by yoanmalie** [brigade/scss-lint#852]
Hi ! 
I've added Sassdoc to my boilerplate who already include scss-lint.
The problem is that i have always errors due to the syntax for comments of Sassdoc `///`.

I'm not able to find a regex who work for the comment style after trying a lot. So i have this errors again and again :

> [W] on line 84 : SpaceAfterComment: Comment literal should be followed by one space 

Because, the linter want a space after the second `/` here: `///`. Not me :smile:.
I want to allow `//` and `///` with one space after them, also allow empty comments.

```
  Comment:
    enabled: true
    allowed: ¯\_(ツ)_/¯
  SpaceAfterComment:
    enabled: true
    style: one_space
    allow_empty_comments: true
```

Thanks !
