### ISSUE TITLE
PropertySortOrder use separate_groups without order

### ISSUE THREAD

**Issue by davidenke** [brigade/scss-lint#893]
The documentation hints, that 
> separate_groups is only enforced if a custom order is specified via the order option.

It would be nice, if `separate_groups` used without `order` would enforce a capsulated order of groups. Every group would be sorted independently (alphabetically by default).

For example this:
```css
video {
      height: auto;
      left: 50%;
      min-height: 100%;
      min-width: 100%;
      position: absolute;
      top: 50%;
      transform: translate(-50%, -50%);
      width: auto;
}
```

would become this:
```css
video {
      height: auto;
      min-height: 100%;
      min-width: 100%;
      width: auto;
      
      position: absolute;
      left: 50%;
      top: 50%;
      transform: translate(-50%, -50%);
}
```

or this:
```css
video {
      min-height: 100%;
      min-width: 100%;

      height: auto;
      width: auto;

      position: absolute;
      left: 50%;
      top: 50%;
      transform: translate(-50%, -50%);
}
```
