### ISSUE TITLE
Alphabetical order error

### ISSUE THREAD

**Issue by jrock2004** [brigade/scss-lint#898]
So on my css file, its giving me error: `csslint: Rule doesn't have all its properties in alphabetical order. (order-alphabetical)`. Its not telling me which ones are out of order. I am using scss-lint with neovim and neomake. Here is example

```css
body {                                                                                    
    font-family: "Open Sans", "Helvetica Neue", "Helvetica", sans-serif;                          
    font-weight: 300;                                                                               
    font-size: 2em;                                                                             
    padding-top: 70px;                                                                              
} 
```

Thoughts?
