### ISSUE TITLE
Some grid properties not declared in properties.txt

### ISSUE THREAD

**Issue by srawlins** [brigade/scss-lint#902]
Lint this SCSS:

```scss
p {
  display: grid;
  grid-template: x;
  grid-template-columns: y;
}
```

```
issue-x.scss:4:3 [W] PropertySpelling: Unknown property grid-template-columns
```

Maybe the few `grid-*` items are from an older grid spec (it's still in draft). Best source for the properties is probably [here](https://drafts.csswg.org/css-grid/#index-defined-here).
