### ISSUE TITLE
Shorthand error with variables followed by value

### ISSUE THREAD

**Issue by michsch** [brigade/scss-lint#91]
I got an error if i use an variable followed by a different value.
So in this case i don't have to write shorthand:

``` scss
$jw-std-margin: 1.5em;

dd {
  margin: 0 0 $jw-std-margin .8em;
}
```

But i get this error message:

``` bash
_typography.scss:152 [W] Shorthand form for property `margin` should be written more concisely as `0 0 $jw-std-margin` instead of `0 0 $jw-std-margin 0`
```

 If i use the variable value itself (`margin: 0 0 1.5em .8em;`), everything went fine and no error occurs.
