### ISSUE TITLE
CleanFilesReporter: comparison of Hash with Hash failed

### ISSUE THREAD

**Issue by AlfredoRamos** [brigade/scss-lint#930]
I get this error when using the `--format=CleanFiles` option:

```shell
$ scss-lint --format=CleanFiles .
comparison of Hash with Hash failed
/home/alfredo/.gem/ruby/2.4.0/gems/scss_lint-0.56.0/lib/scss_lint/reporter/clean_files_reporter.rb:7:in `sort'                                                                                          
/home/alfredo/.gem/ruby/2.4.0/gems/scss_lint-0.56.0/lib/scss_lint/reporter/clean_files_reporter.rb:7:in `report_lints'                                                                                  
/home/alfredo/.gem/ruby/2.4.0/gems/scss_lint-0.56.0/lib/scss_lint/cli.rb:193:in `block in report_lints'                                                                                                 
/home/alfredo/.gem/ruby/2.4.0/gems/scss_lint-0.56.0/lib/scss_lint/cli.rb:192:in `each'              
/home/alfredo/.gem/ruby/2.4.0/gems/scss_lint-0.56.0/lib/scss_lint/cli.rb:192:in `report_lints'      
/home/alfredo/.gem/ruby/2.4.0/gems/scss_lint-0.56.0/lib/scss_lint/cli.rb:68:in `scan_for_lints'     
/home/alfredo/.gem/ruby/2.4.0/gems/scss_lint-0.56.0/lib/scss_lint/cli.rb:59:in `act_on_options'     
/home/alfredo/.gem/ruby/2.4.0/gems/scss_lint-0.56.0/lib/scss_lint/cli.rb:33:in `run'                
/home/alfredo/.gem/ruby/2.4.0/gems/scss_lint-0.56.0/bin/scss-lint:7:in `<top (required)>'           
/home/alfredo/.gem/ruby/2.4.0/bin/scss-lint:23:in `load'                                            
/home/alfredo/.gem/ruby/2.4.0/bin/scss-lint:23:in `<main>'
```
SCSS-Lint version: 0.56.0
Sass version: 3.5.3
Ruby version: 2.4.2
.scss-lint.yml
```yaml
scss_files:
  - 'scss/**/*.scss'

linters:
  BorderZero:
    enabled: true
    convention: none
  Comment:
    enabled: true
    exclude:
      - scss/main.scss
  ChainedClasses:
    enabled: true
  Indentation:
    enabled: true
    character: tab
    width: 1
  PropertySortOrder:
    enabled: true
    order: concentric
```
