### ISSUE TITLE
DuplicateProperty should not produce a lint when including a fallback for env()

### ISSUE THREAD

**Issue by srawlins** [brigade/scss-lint#948]
iOS 11 and the iPhone X have the notch thing, and safe areas and all, which can be styled around using `env()` (or `constant()` in iOS 11.0 I guess). But fallbacks still need to be produced for browsers that don't understand `env()`. Taken from [an ayogo blog post](https://ayogo.com/blog/ios11-viewport/):

```css
header {
    /* ... */

    /* Status bar height on iOS 10 */
    padding-top: 20px;

    /* Status bar height on iOS 11.0 */
    padding-top: constant(safe-area-inset-top);

    /* Status bar height on iOS 11+ */
    padding-top: env(safe-area-inset-top);
}
```

DuplicateProperty should recognize that: properties with a value that is an `env()` function call (or I suppose `constant()` function call) should not be considered duplicate.

In the meantime of course, you can use `ignore_consecutive`.
